package MakeItRain.Data;

import cpw.mods.fml.common.ModMetadata;

public class ModData {
    public static final String ID = "makeitrain";
    public static final String NAME = "Make It Rain";
    public static final String VERSION = "0.0";
    public static final String DEPENDENCIES = "";

    public static void setMetadata(ModMetadata data) {
        data.autogenerated = false;
        data.url = "http://github.com/doubly/MakeItRain";
        data.credits = "...";
        data.authorList.add("Knaught");
        data.description = "Making it rain!";
        data.logoFile = "";
        data.updateUrl = "";
        data.parent = "";
    }

}